name: Bug Report
description: Report an issue for WEBSTUDIO IMS
title: "[{title}] "
labels: []
body:
  - type: textarea
    id: platform
    attributes:
      label: Platform
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
