name: Feature Request
description: Report an issue for WEBSTUDIO IMS
title: "[{title}] "
labels: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance
    validations:
      required: true
