"""Default system setting keys and values."""

from __future__ import annotations

from webstudio_backend.infrastructure.database.enums import SettingValueType

SETTING_DEFAULTS: dict[str, tuple[str, SettingValueType]] = {
    "company_name": ("", SettingValueType.STRING),
    "company_logo": ("", SettingValueType.STRING),
    "company_address": ("", SettingValueType.STRING),
    "gst_number": ("", SettingValueType.STRING),
    "company_phone": ("", SettingValueType.STRING),
    "company_email": ("", SettingValueType.STRING),
    "default_store_id": ("", SettingValueType.STRING),
    "default_language": ("en", SettingValueType.STRING),
    "timezone": ("Asia/Kolkata", SettingValueType.STRING),
    "currency": ("INR", SettingValueType.STRING),
    "session_timeout_minutes": ("15", SettingValueType.INTEGER),
    "password_min_length": ("10", SettingValueType.INTEGER),
    "password_require_uppercase": ("true", SettingValueType.BOOLEAN),
    "password_require_lowercase": ("true", SettingValueType.BOOLEAN),
    "password_require_number": ("true", SettingValueType.BOOLEAN),
    "password_require_symbol": ("false", SettingValueType.BOOLEAN),
    "password_history_count": ("5", SettingValueType.INTEGER),
    "remember_me_ttl_days": ("30", SettingValueType.INTEGER),
    "lockout_threshold": ("5", SettingValueType.INTEGER),
    "lockout_duration_minutes": ("15", SettingValueType.INTEGER),
    "default_inventory_status": ("received", SettingValueType.STRING),
    "qr_code_enabled": ("true", SettingValueType.BOOLEAN),
    "auto_generate_labels": ("false", SettingValueType.BOOLEAN),
    "serial_number_prefix": ("", SettingValueType.STRING),
    "serial_number_suffix": ("", SettingValueType.STRING),
    "inventory_colors": ("[]", SettingValueType.JSON),
    "default_payment_modes": ('["Cash","UPI","Card","Finance"]', SettingValueType.JSON),
    "invoice_prefix": ("INV-", SettingValueType.STRING),
    "manual_sale_enabled": ("true", SettingValueType.BOOLEAN),
    "tally_enabled": ("false", SettingValueType.BOOLEAN),
    "tally_host": ("127.0.0.1", SettingValueType.STRING),
    "tally_port": ("9000", SettingValueType.STRING),
    "tally_company_name": ("WEBSTUDIO", SettingValueType.STRING),
    "tally_sync_interval_seconds": ("300", SettingValueType.INTEGER),
    "gemini_api_key": ("", SettingValueType.STRING),
    "gemini_model": ("gemini-2.5-flash", SettingValueType.STRING),
    "ai_primary_provider": ("gemini", SettingValueType.STRING),
    "ai_fallback_chain": ('["gemini"]', SettingValueType.JSON),
    "ai_enrichment_enabled": ("true", SettingValueType.BOOLEAN),
    "ai_timeout_seconds": ("90", SettingValueType.INTEGER),
    "ai_retry_count": ("2", SettingValueType.INTEGER),  # total lookup attempts (includes first try)
    "groq_api_key": ("", SettingValueType.STRING),
    "groq_model": ("llama-3.3-70b-versatile", SettingValueType.STRING),
    "openrouter_api_key": ("", SettingValueType.STRING),
    "openrouter_model": ("meta-llama/llama-3.3-70b-instruct:free", SettingValueType.STRING),
    "excel_export_path": ("exports", SettingValueType.STRING),
    "excel_file_naming": ("webstudio-{report}-{date}", SettingValueType.STRING),
    "notifications_enabled": ("true", SettingValueType.BOOLEAN),
    "desktop_notifications": ("true", SettingValueType.BOOLEAN),
    "system_alerts_enabled": ("true", SettingValueType.BOOLEAN),
    "tally_alerts_enabled": ("true", SettingValueType.BOOLEAN),
    "inventory_alerts_enabled": ("true", SettingValueType.BOOLEAN),
    "audit_alerts_enabled": ("true", SettingValueType.BOOLEAN),
    "backup_alerts_enabled": ("true", SettingValueType.BOOLEAN),
    "backup_folder": ("backups", SettingValueType.STRING),
    "backup_schedule": ("manual", SettingValueType.STRING),
    "backup_retention_count": ("30", SettingValueType.INTEGER),
    "backup_retention_policy": ("last_30", SettingValueType.STRING),
    "backup_storage_backend": ("local", SettingValueType.STRING),
    "last_backup_at": ("", SettingValueType.STRING),
    "mobile_latest_version": ("0.1.0", SettingValueType.STRING),
    "mobile_release_date": ("", SettingValueType.STRING),
    "mobile_release_notes": ("", SettingValueType.STRING),
    "mobile_apk_download_url": ("", SettingValueType.STRING),
    "mobile_release_channel": ("stable", SettingValueType.STRING),
}
